// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ToggleDemoMode(arg1) {
  return window['go']['main']['App']['ToggleDemoMode'](arg1);
}

export function TrackTicker(arg1) {
  return window['go']['main']['App']['TrackTicker'](arg1);
}
