// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ToggleDemoMode(arg1:boolean):Promise<void>;

export function TrackTicker(arg1:string):Promise<string>;
